### ISSUE TITLE
refactor : doctorqna 리팩토링

### ISSUE THREAD

**Issue by Shin-sangwon** [likelion-backendschool/animal-care#101]
## Description

기능추가, 전체적인 구조 개선 및 컨트롤러 테스트코드 추가 
Service에서 Dto대신 Entity 반환하게 수정하기 (https://www.inflearn.com/questions/139564/dto-%EC%82%AC%EC%9A%A9%EC%8B%9C%EA%B8%B0%EC%97%90-%EB%8C%80%ED%95%9C-%EC%A7%88%EB%AC%B8)

## Todo

- [ ] 컨트롤러 테스트코드 추가
- [ ] @ControllerAdvice를 통해 에러 핸들링 및 에러페이지 추가
- [ ] 메소드 로직 개선
- [ ] 해시태그 기능 추가

**Comment by doolysmile** [comment]
확인했습니다.
