### ISSUE TITLE
feat : 로그인시 Valid 처리, 로그인 했을 경우와 안 했을 경우 보이는 창 수정

### ISSUE THREAD

**Issue by doolysmile** [likelion-backendschool/animal-care#52]
## Description

> 로그인 관련 기능 추가

## Todo

- [x] 로그인 valid 처리
- [x] 로그인 했을 시 SignUp 메뉴 안보이게 수정(Sign Out 나오도록)
- [x] 로그인한 사용자에 따라 MyPage가 다르게 보이도록 수정
- [x] 로그인 페이지에 레이아웃 적용
- [ ] 회원가입시 동물 추가
