### ISSUE TITLE
feat : 동물 관리 페이지 

### ISSUE THREAD

**Issue by doolysmile** [likelion-backendschool/animal-care#57]
## Description

> 동물 관리 페이지 

## Todo

- [x] 동물 관리 api 구현
- [x] 동물 관리 뷰 구현
- [ ] 회원가입 후 동물 관리 페이지로 리다이렉팅
- [ ] global util에 알림 창 띄우는 기능 만들기
