### ISSUE TITLE
refactor : 마이페이지 url수정 및 security 설정

### ISSUE THREAD

**Issue by ChangMinSuh** [likelion-backendschool/animal-care#65]
## Description

> description

## Todo

- [x] doctor 마이페이지 url 수정
- [x] member 마이페이지 url 수정
- [x] security config에 url에 따른 권한 수정
