### ISSUE TITLE
refactor: 비대면진료 화면 수정

### ISSUE THREAD

**Issue by brightGarden02** [likelion-backendschool/animal-care#73]
## Description
>비대면진료 화면 수정

## Todo
- [x]  화면이 iframe안에서 진단서 작성완료 버튼을 누르면 져쟝후 예약내역으로 돌아가도록 구현
- [x] 진단서에 동물 부가정보 연동
- [x] 수의사 엔터티에 면허 변수 추가 빛 진단서와 연동
