### ISSUE TITLE
refactor : Community view 수정

### ISSUE THREAD

**Issue by muyongKim** [likelion-backendschool/animal-care#78]
## Description
> 커뮤니티 view 수정 

## Todo

- [x] 페이징 로직 doctor QnA와 통일
- [ ] 게시글 검색 기능 추가
- [ ] 게시글 추천 -> Like로 수정
- [ ] 게시글 디테일 view 수정
