### ISSUE TITLE
refactor : doctorqna refactoring

### ISSUE THREAD

**Issue by Shin-sangwon** [likelion-backendschool/animal-care#82]
## Description

코드 리팩토링

## Todo

- [ ] 안쓰는 import 삭제
- [ ] import에 와일드카드 삭제
- [ ] 안쓰는 메서드 삭제
- [ ] 간단한 리팩토링
