### ISSUE TITLE
test : communityService 테스트 코드

### ISSUE THREAD

**Issue by doolysmile** [likelion-backendschool/animal-care#99]
## Description

> communityService 테스트 코드 작성

## Todo

- [ ] 테스트 환경 구성
- [ ] community 테스트 코드 작성
- [ ] community 추가기능 구현

**Comment by Shin-sangwon** [comment]
화이팅하세요
